services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - server-v-node-modules:/node_modules
    depends_on:
      database:
        condition: service_healthy
  database:
    build:
      context: ./lib/db
      dockerfile: Dockerfile
    container_name: postgres
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-v:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"
