services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
  database:
    build:
      context: ./lib/db
      dockerfile: Dockerfile
    container_name: postgres
    env_file: .env.docker
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-v:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  database-v:
    name: "database-v"
